### ISSUE TITLE
Default save to remote directory? 

### ISSUE THREAD

**Issue by CodeBroJohn** [react-pdf/site#29]
When using the pdfdownloadlink  is it possible to default the save to a remote directory?

**Comment by idrtabd** [comment]
Less of an issue, more of a How To.   I don't see instructions for running on the server and saving to a file.  I want to generate PDFs without using a browser.
All i see in the documentation is:
ReactPDF.render(<MyDocument />, `${__dirname}/example.pdf`);

**Comment by diegomura** [comment]
Here: https://react-pdf.org/node

**Comment by idrtabd** [comment]
> Here: https://react-pdf.org/node

Thanks, I came across this earlier, I was excited that this was possible, but there's just a code snippet.  I don't understand that paradigm, I've made some simple node apps, but I do most of my work in standard web react.  How do I set up a node project that's running React with no browser?
